# -*- coding: utf-8 -*-
"""Total-Casa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P0T7CqPKKvo-mdSQAkTE-ZSiJsBDEtn3
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd  # Import pandas

# Specify the file path
file_path = '/content/drive/My Drive/TotalCasas/Total-Casas.xlsx'

# Read the Excel file
data = pd.read_excel(file_path)

# Display the first few rows of the data
print(data.head())

!pip install seaborn

# Create dashboard-Characteristics
import matplotlib.pyplot as plt
import seaborn as sns

# Apply Seaborn's default style
sns.set_theme()

fig = plt.figure(figsize=(30, 50))

plt.subplot(2, 2, 1)
# Replace 'df' with 'data'
developer_units = data.groupby('Desarrollador')['Total Unidades'].sum().sort_values(ascending=True)
developer_units.plot(kind='barh')
plt.title('Total Units by Developer')
plt.xlabel('Number of Units')

# 2. Price Distribution
plt.subplot(2, 2, 2)
sns.boxplot(y='Desarrollador', x='$ Lista', data=data)  # Change df to data
plt.title('Distribution Price by Developer')
plt.ylabel('Developer')
plt.xlabel('Price ($ List)')

# 3. Sales vs Inventory
plt.subplot(2, 2, 3)
# Replace 'df' with 'data' to use the DataFrame loaded earlier
df_summary = data.groupby('Desarrollador').agg({
    'Ventas': 'sum',
    'Inventario': 'sum'
}).reset_index()

x = range(len(df_summary['Desarrollador']))
width = 0.35

plt.bar(x, df_summary['Ventas'], width=width, label='Sales')
plt.bar([i + width for i in x], df_summary['Inventario'], width, label='Inventory')
plt.xticks([i + width/2 for i in x], df_summary['Desarrollador'], rotation=45)
plt.legend()
plt.title('Sales vs Inventory by Developer')

# 4. Construction vs Land Area
plt.subplot(2, 2, 4)
# Replace 'df' with 'data' to access the correct DataFrame
plt.scatter(data['Terreno (m2 T)'], data['Construcción (m2 C)'])
plt.xlabel('Land (m²)')
plt.ylabel('Construction (m²)')
plt.title('Construction vs Land')


plt.tight_layout()
plt.show()

print('\
Statistics:')
print('Total de Projectos:', len(data))  # Change df to data
print('Average Precio:', data['$ Lista'].mean())  # Change df to data
print('Total Unidades:', data['Total Unidades'].sum())  # Change df to data
print('Total Ventas:', data['Ventas'].sum())  # Change df to data
print('Total Inventario:', data['Inventario'].sum())  # Change df to data